# Generated by Django 5.0.4 on 2024-04-22 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vaccin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('completed', models.BooleanField(default=False)),
                ('decsription', models.CharField(max_length=500, null=True)),
                ('ageindays', models.IntegerField()),
            ],
        ),
    ]
