# Generated by Django 5.0.4 on 2024-04-30 07:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('child', '0002_remove_mother_child_child_motherid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='child',
            old_name='motherID',
            new_name='mother',
        ),
    ]
