# Generated by Django 5.0.4 on 2024-04-30 07:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('child', '0003_rename_motherid_child_mother'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='child',
            name='mother',
        ),
    ]
