# Generated by Django 5.0.4 on 2024-05-03 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fever', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fever',
            name='chronic_diseases',
            field=models.BooleanField(default=False, verbose_name='Chronic diseases'),
        ),
        migrations.AddField(
            model_name='fever',
            name='diarrhea_duration',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Diarrhea Duration (days)'),
        ),
        migrations.AddField(
            model_name='fever',
            name='fever_duration',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Fever Duration (days)'),
        ),
        migrations.AddField(
            model_name='fever',
            name='tummy_ache',
            field=models.BooleanField(default=False, verbose_name='Tummy_ache'),
        ),
    ]
