# Generated by Django 5.0.4 on 2024-05-03 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fever', '0004_fever_result'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fever',
            name='diarrhea_duration',
        ),
        migrations.RemoveField(
            model_name='fever',
            name='fever_duration',
        ),
    ]
