# Generated by Django 5.0.4 on 2024-05-04 10:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('childs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fever',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperature', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Temperature')),
                ('fever', models.BooleanField(default=False, verbose_name='Fever')),
                ('cough', models.BooleanField(default=False, verbose_name='Cough')),
                ('runny_nose', models.BooleanField(default=False, verbose_name='Runny Nose')),
                ('difficulty_breathing', models.BooleanField(default=False, verbose_name='Difficulty Breathing')),
                ('diarrhea', models.BooleanField(default=False, verbose_name='Diarrhea')),
                ('vomiting', models.BooleanField(default=False, verbose_name='Vomiting')),
                ('dehydration', models.BooleanField(default=False, verbose_name='Dehydration')),
                ('lack_of_activity', models.BooleanField(default=False, verbose_name='Lack of Activity')),
                ('irritability', models.BooleanField(default=False, verbose_name='Irritability')),
                ('chronic_diseases', models.BooleanField(default=False, verbose_name='Chronic diseases')),
                ('tummy_ache', models.BooleanField(default=False, verbose_name='Tummy_ache')),
                ('others', models.TextField(blank=True, verbose_name='Other Symptoms')),
                ('result', models.CharField(default='yes', max_length=255, verbose_name='Result')),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='childs.child')),
            ],
        ),
    ]
